spring:
  main:
    banner-mode: 'off'
  application:
    name: ComputerHardware
  messages:
    basename: i18n.messages
  data:
    mongodb:
      uri: mongodb://localhost:27017/computerHardware
      database: computerHardware
application:
  nosql:
    type: mongo

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  migrationScanPackage:
    - computerHardware.migration