spring:
  main:
    banner-mode: 'off'
  application:
    name: computerHardware
  data:
    mongodb:
      database: computerHardware
      port: 27017
      host: localhost
#      uri: mongodb://localhost:27017/library?replicaSet=test&connectTimeoutMS=120000
#      replicaSet=rs0&readPreference=primaryPreferred&retryWrites=false&maxIdleTimeMS=30000

application:
  locale: ru

server:
  port: 9090


